# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
    - uses: actions/checkout@v2
      
    - name: Setup Python      
      uses: actions/setup-python@v1.2.0
      with:
        python-version: '3.7.4'
        architecture: 'x64'
      
    - name: Install flake8 
      run: pip install flake8
      
    - name: Install Requiriments
      run: pip install -r requirements.txt   
      
    - name: Install Requiriments
      run: flake8 .
      
    - name: Run Tests
      run: python -m unittest
